FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . . 
RUN dotnet publish -c Release -o output



# for blazor server
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /src
COPY --from=build /src/output/wwwroot .
ENTRYPOINT ["dotnet", "dotnetapp.dll"]
